import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Image src="/images/tucks2.jpeg" alt="truck" width={624} height={468} />
        <h2 className={styles.title}>

        EXCLUSIVE TRUCKS & CARS
        </h2>

        <span className={styles.description}>
          Comming soon<br></br>
          (305) 733-0126<br></br>
          2900 SW 69th CT MIAMI, FL 3315
        </span>
       
       
          

        <div className={styles.grid}>
          

          

          

         
        </div>
      </main>

      <footer className={styles.footer}>
        
         
      </footer>
    </div>
  )
}
